baseURL = "https://olografix.org/"
enableRobotsTXT = true
languageCode = 'it'

buildFuture = true

defaultContentLanguage = 'it'
defaultContentLanguageInSubdir = false
[languages]
  [languages.it]
    languageCode = 'it-IT'
    languageName = 'IT'
    title = 'Metro Olografix'
    weight = 1
    contentDir = "content/italiano"
    [languages.it.permalinks]
      progetti = "progetti/:slug"
    [languages.it.params]
      description = "Metro Olografix è un’associazione fondata nel 1994 a Pescara che abbraccia la cultura digitale libera, nata per condividere e diffondere la passione per la sicurezza informatica, i diritti digitali e la creatività hacker."
  [languages.en]
    languageCode = 'en-US'
    languageName = 'EN'
    title = 'Metro Olografix'
    contentDir = "content/english"
    weight = 2
    [languages.en.permalinks]
      progetti = "projects/:slug"
      attivita = "activities/:slug"
      associazione = "association/:slug"
    [languages.en.params]
      description = "Metro Olografix is an association founded in 1994 in Pescara that embraces free digital culture, established to share and spread a passion for cybersecurity, digital rights and hacker creativity."
  [languages.es]
    languageCode = 'es-VE'
    languageName = 'ES'
    title = 'Metro Olografix'
    contentDir = "content/spanish"
    weight = 2
    [languages.es.permalinks]
      progetti = "projects/:slug"
      attivita = "activities/:slug"
      associazione = "association/:slug"
    [languages.es.params]
      description = "Metro Olografix es una asociacion fundada en el 1994 en Pescara que abraza la cultura digital libre, establecida para compartir y difundir una pasion por la cyberseguridad, derechos digitales y creatividad hacker."
[markup.goldmark.renderer]
  unsafe = true

[[build.cachebusters]]
source = "JSON"
target = ".*"

[params]
  image = "images/metro-dark-preview.png"
  galleryServer = "https://gallery.olografix.org"

  archiveOldSite = "https://web.archive.org/web/20241002224544/https://www.olografix.org/"

  github = "https://github.com/Metro-Olografix"
  instagram = "https://www.instagram.com/metroolografix"
  linkedin = "https://it.linkedin.com/company/metro-olografix"
  facebook = "https://www.facebook.com/MetroOlografix"

  [[params.direttivo]]
    name = "Michelangelo Morrillo"
    nickname = "pinguino"
    role = "presidente"

  [[params.direttivo]]
    name = "Elena Santomieri"
    nickname = "00ele"
    role = "vice presidente"
  
  [[params.direttivo]]
    name = "Simona Forti"
    nickname = "nhaima"
    role = "tesoriere"
  
  [[params.direttivo]]
    name = "Lucia Zappacosta"
    nickname = "kundera"
    role = "consigliere"

  [[params.direttivo]]
    name = "Stefano Chiccarelli"
    nickname = "neuro"
    role = "consigliere"

  [[params.direttivo]]
    name = "Igor Falcomatà"
    nickname = "koba"
    role = "consigliere"

[[redirects]]
  from = '/**'
  status = 404
  to = '/404.html'

[outputs]
  home = ["HTML", "ICS"]

[outputFormats]
  [outputFormats.ICS]
    mediaType = "text/calendar"
    baseName = "calendar"
    isPlainText = true
    notAlternative = true
